'use client';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { Phone, Star, MapPin, ArrowRight, Check, MessageCircle, Droplets, Car, Zap, BadgeCheck, CalendarCheck, ThumbsUp, Shield } from 'lucide-react';

function HeroSection() {
    const handleBooking = () => { window.open('https://wa.me/32472303701?text=Bonjour Nathan ! Je souhaite réserver un lavage voiture à Melen. 🚗', '_blank'); };
    return (
        <section className="relative min-h-[100svh] flex flex-col justify-center bg-gradient-to-b from-white via-sky-50/30 to-white pt-16 pb-8 sm:pt-24 sm:pb-12 overflow-hidden">
            <div className="absolute inset-0 overflow-hidden pointer-events-none"><div className="absolute top-20 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-gradient-to-br from-sky-100/60 via-blue-50/40 to-transparent rounded-full blur-3xl" /></div>
            <div className="relative container mx-auto px-5 z-10 flex-1 flex flex-col justify-center">
                <div className="max-w-3xl mx-auto">
                    <motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className="flex justify-center mb-6"><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white border border-slate-200/80 shadow-sm"><MapPin className="w-4 h-4 text-sky-500" /><span className="text-xs font-semibold text-slate-700">Déplacement gratuit à Melen</span></div></motion.div>
                    <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-6">
                        <h1 className="font-display text-[2.5rem] leading-[1.1] sm:text-5xl md:text-6xl font-extrabold tracking-tight text-slate-900 mb-4">Lavage voiture{' '}<span className="relative inline-block"><span className="relative z-10 bg-gradient-to-r from-sky-500 to-emerald-500 bg-clip-text text-transparent">à Melen</span><span className="absolute -bottom-1 left-0 right-0 h-3 bg-gradient-to-r from-sky-200 to-emerald-200 -z-10 -rotate-1 rounded" /></span></h1>
                        <p className="text-lg sm:text-xl text-slate-600 max-w-xl mx-auto leading-relaxed">Valeting au cœur des <strong className="text-slate-900">bocages du Pays de Herve</strong>. Vergers, prairies et haies = pollen et poussière. On s'en charge.</p>
                    </motion.div>
                    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col gap-3 mb-8">
                        <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} onClick={handleBooking} className="w-full sm:w-auto sm:mx-auto group relative overflow-hidden px-8 py-5 bg-slate-900 text-white font-bold text-lg rounded-2xl shadow-2xl"><span className="relative z-10 flex items-center justify-center gap-3"><CalendarCheck className="w-5 h-5" /> Réserver à Melen <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" /></span><div className="absolute inset-0 bg-gradient-to-r from-sky-600 to-emerald-600 opacity-0 group-hover:opacity-100 transition-opacity" /></motion.button>
                        <div className="flex items-center justify-center gap-4 text-sm text-slate-500"><a href="https://wa.me/32472303701" className="flex items-center gap-1.5 hover:text-green-600"><MessageCircle className="w-4 h-4" /> WhatsApp</a><span className="w-1 h-1 bg-slate-300 rounded-full" /><a href="tel:+32472303701" className="flex items-center gap-1.5 hover:text-sky-600"><Phone className="w-4 h-4" /> 0472 30 37 01</a></div>
                    </motion.div>
                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex flex-wrap justify-center gap-x-6 gap-y-3 text-sm">{[{ icon: Zap, text: 'Résultat en 90 min' }, { icon: BadgeCheck, text: 'Produits Pro' }, { icon: ThumbsUp, text: 'Satisfait ou refait' }].map(({ icon: Icon, text }) => (<div key={text} className="flex items-center gap-2 text-slate-600"><div className="w-7 h-7 rounded-lg bg-sky-50 flex items-center justify-center"><Icon className="w-4 h-4 text-sky-600" /></div><span className="font-medium">{text}</span></div>))}</motion.div>
                </div>
            </div>
        </section>
    );
}

function BenefitsSection() {
    const benefits = [{ icon: Car, title: "Expert Pays de Herve", description: "Pollen des vergers, poussière des chemins, résidus agricoles... On connaît les défis du plateau.", color: "sky" }, { icon: Droplets, title: "Traitement campagne", description: "Fientes d'oiseaux, résine, sève des haies bocagères. On élimine tout sans abîmer la peinture.", color: "emerald" }, { icon: Shield, title: "Isolé ? On vient", description: "Même les fermes et hameaux les plus reculés du plateau. Déplacement gratuit à Melen.", color: "violet" }];
    const colorClasses = { sky: "bg-sky-50 text-sky-600 border-sky-100", emerald: "bg-emerald-50 text-emerald-600 border-emerald-100", violet: "bg-violet-50 text-violet-600 border-violet-100" };
    return (<section className="py-16 sm:py-20 bg-white"><div className="max-w-6xl mx-auto px-5"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-10"><h2 className="font-display text-2xl sm:text-3xl md:text-4xl font-bold text-slate-900">Pourquoi choisir Shine&Go à Melen ?</h2></motion.div><div className="grid sm:grid-cols-3 gap-4">{benefits.map((b, i) => (<motion.div key={b.title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }} className="p-6 rounded-2xl bg-slate-50/50 border border-slate-100 hover:bg-white hover:shadow-lg transition-all"><div className={`w-12 h-12 rounded-xl ${colorClasses[b.color as keyof typeof colorClasses]} border flex items-center justify-center mb-4`}><b.icon className="w-6 h-6" /></div><h3 className="font-display text-lg font-bold text-slate-900 mb-2">{b.title}</h3><p className="text-slate-600 text-sm">{b.description}</p></motion.div>))}</div></div></section>);
}

function ServicesSection() {
    const services = [{ title: 'Intérieur', price: '80', icon: '🧹', features: ['Aspiration complète', 'Nettoyage plastiques', 'Vitres intérieures'], href: '/lavage-interieur-voiture', accent: 'from-amber-400 to-orange-500' }, { title: 'Extérieur', price: '80', icon: '🚗', features: ['Lavage main premium', 'Jantes & pneus', 'Cire protection'], href: '/lavage-exterieur-voiture', accent: 'from-sky-400 to-blue-500' }, { title: 'Complet', price: '150', icon: '✨', features: ['Tout inclus', '90 min intervention', 'Résultat showroom'], href: '/lavage-complet-voiture', accent: 'from-emerald-400 to-teal-500', popular: true }];
    return (<section className="py-16 sm:py-24 bg-gradient-to-b from-slate-50 to-white"><div className="max-w-6xl mx-auto px-5"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-10"><span className="inline-block px-3 py-1 text-xs font-bold text-sky-600 bg-sky-50 rounded-full mb-3 uppercase">Nos formules</span><h2 className="font-display text-2xl sm:text-3xl font-bold text-slate-900 mb-3">Tarifs lavage voiture à Melen</h2></motion.div><div className="grid md:grid-cols-3 gap-4 mb-8">{services.map((s, i) => (<motion.div key={s.title} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }} className="relative group">{s.popular && <div className="absolute -top-3 left-1/2 -translate-x-1/2 z-10"><span className="px-4 py-1.5 bg-gradient-to-r from-emerald-500 to-teal-500 text-white text-xs font-bold rounded-full shadow-lg">⭐ Le + populaire</span></div>}<Link href={s.href} className="block h-full"><div className={`h-full p-6 rounded-2xl bg-white border-2 ${s.popular ? 'border-emerald-200 shadow-xl' : 'border-slate-100 hover:shadow-xl'}`}><div className="flex items-start justify-between mb-4"><div className={`w-14 h-14 rounded-xl bg-gradient-to-br ${s.accent} flex items-center justify-center text-2xl shadow-lg`}>{s.icon}</div><div className="text-right"><span className="text-3xl font-extrabold text-slate-900">{s.price}</span><span className="text-lg font-bold text-slate-400">€</span></div></div><h3 className="font-display text-xl font-bold text-slate-900 mb-2">Lavage {s.title}</h3><ul className="space-y-2 mb-5">{s.features.map((f) => (<li key={f} className="flex items-center gap-2 text-sm text-slate-700"><Check className={`w-4 h-4 ${s.popular ? 'text-emerald-500' : 'text-sky-500'}`} />{f}</li>))}</ul><div className={`flex items-center gap-2 text-sm font-semibold ${s.popular ? 'text-emerald-600' : 'text-sky-600'}`}>Voir les détails <ArrowRight className="w-4 h-4" /></div></div></Link></motion.div>))}</div></div></section>);
}

function CTASection() {
    const handleBooking = () => { window.open('https://wa.me/32472303701?text=Bonjour Nathan ! Je souhaite réserver un lavage voiture à Melen. 🚗', '_blank'); };
    const zones = ['Herve', 'Battice', 'Soumagne', 'Liège'];
    return (<section className="relative py-16 sm:py-24 overflow-hidden"><div className="absolute inset-0 bg-slate-900" /><div className="absolute inset-0 bg-gradient-to-br from-sky-900/50 via-slate-900 to-emerald-900/30" /><div className="relative max-w-4xl mx-auto px-5 text-center"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><h2 className="font-display text-3xl sm:text-4xl font-bold text-white mb-4">Prêt pour une voiture comme neuve ?</h2><p className="text-lg text-white/70 mb-8">Réservez votre lavage en 2 minutes.</p><div className="flex flex-col sm:flex-row gap-3 justify-center mb-10"><motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} onClick={handleBooking} className="group px-8 py-4 bg-white text-slate-900 font-bold text-lg rounded-xl shadow-2xl flex items-center justify-center gap-3"><CalendarCheck className="w-5 h-5" /> Réserver <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" /></motion.button><motion.a href="tel:+32472303701" whileHover={{ scale: 1.02 }} className="px-8 py-4 bg-white/10 text-white font-bold text-lg rounded-xl border border-white/20 flex items-center justify-center gap-3"><Phone className="w-5 h-5" /> 0472 30 37 01</motion.a></div><div className="pt-8 border-t border-white/10"><p className="text-sm text-white/50 mb-4"><MapPin className="w-4 h-4 inline mr-1" />Zones proches</p><div className="flex flex-wrap justify-center gap-2">{zones.map((z) => (<Link key={z} href={`/lavage-voiture-${z.toLowerCase()}`} className="px-3 py-1.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg text-sm text-white/70 hover:text-white">{z}</Link>))}</div></div></motion.div></div></section>);
}

export default function MelenClient() { return (<div className="bg-white -mt-16 md:-mt-20"><HeroSection /><BenefitsSection /><ServicesSection /><CTASection /></div>); }
